const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
  queryStatus: () => ipcRenderer.invoke("status:query"),
  startAll: () => ipcRenderer.invoke("all:start"),
  envCheck: () => ipcRenderer.invoke("env:check"),
  relayStart: () => ipcRenderer.invoke("relay:start"),
  relayStop: () => ipcRenderer.invoke("relay:stop"),
  watcherStart: () => ipcRenderer.invoke("watcher:start"),
  watcherStop: () => ipcRenderer.invoke("watcher:stop"),
  refreshPoints: () => ipcRenderer.invoke("points:refresh"),
  registerZcode: () => ipcRenderer.invoke("zcode:register"),
  zcodeCheck: () => ipcRenderer.invoke("zcode:check"),
  syncCredential: () => ipcRenderer.invoke("credential:sync"),
  smokeTest: () => ipcRenderer.invoke("smoke:test"),
  workbuddyStart: () => ipcRenderer.invoke("workbuddy:start"),
  workbuddyStop: () => ipcRenderer.invoke("workbuddy:stop"),
  workbuddySmoke: () => ipcRenderer.invoke("workbuddy:smoke"),
  workbuddyCredits: () => ipcRenderer.invoke("workbuddy:credits"),
  traeStart: () => ipcRenderer.invoke("trae:start"),
  traeStop: () => ipcRenderer.invoke("trae:stop"),
  traeSmoke: () => ipcRenderer.invoke("trae:smoke"),
  doubaoStart: () => ipcRenderer.invoke("doubao:start"),
  doubaoStop: () => ipcRenderer.invoke("doubao:stop"),
  doubaoSmoke: () => ipcRenderer.invoke("doubao:smoke"),
  doubaoSyncCookies: (opts) => ipcRenderer.invoke("doubao:sync-cookies", opts),
  comateStart: () => ipcRenderer.invoke("comate:start"),
  comateStop: () => ipcRenderer.invoke("comate:stop"),
  comateSmoke: () => ipcRenderer.invoke("comate:smoke"),
  qoderStart: () => ipcRenderer.invoke("qoder:start"),
  qoderStop: () => ipcRenderer.invoke("qoder:stop"),
  qoderSmoke: () => ipcRenderer.invoke("qoder:smoke"),
  qoderSyncAccounts: () => ipcRenderer.invoke("qoder:sync-accounts"),
  qwenworkSmoke: () => ipcRenderer.invoke("qwenwork:smoke"),
  tailLog: (which) => ipcRenderer.invoke("logs:tail", which),
});
